version: "3.8"

services:   
  postgres-db:
    image: postgres:17
    volumes:
      - ./postgres-db/pgdata:/pgdata
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA=/pgdata

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres-db

  go-api:
    image: golang:1.23.5-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: go run main.go api
    environment:
      - DB_HOST=postgres-db:5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD} 
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres-db
      - migrate